# version: "3.8"
# services:
#   backend_sample:
#     container_name: backend_sample_container
#     build:
#       context: .
#       dockerfile: Dockerfile.dev # build image from Dockerfile
#     restart: always
#     ports:
#       - 4000:4000
#     env_file: ./src/configs/.env.development
#     environment:
#       - DOCKER_ENV=true #docker compose is as dcoker but  can run alot of contaniners in one time . image & container
#     volumes:
#       - ./src:/app/src # HOT RELOADING, ANY CHANGE IN SRC FOLDER OUR APP WILL RESTART
version: "3.8"
services:
  backend_sample:
    container_name: backend_sample_container
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    env_file: ./src/configs/.env.development
    environment:
      - DOCKER_ENV=true
    depends_on:
      - mongo_db
    volumes:
      - ./src:/app/src # Local src folder mapped to /app/src in the container

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Huor
      - MONGO_INITDB_ROOT_PASSWORD=huor123456
    volumes:
      - mongo_data:/data/db # Persists MongoDB data in a Docker volume

volumes:
  mongo_data:
