version: "3.8"
services:
  backend_sample_app:
    image: backend_sample_app:latest
    container_name: backend_sample_app
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 4000:4000
    env_file: ./src/configs/.env.development
    environment:
      - DOCKER_ENV=true
